# Generated by Django 3.0.3 on 2020-05-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
