# Generated by Django 3.1.1 on 2020-11-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('stock', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
