# Generated by Django 3.1.3 on 2021-01-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_spareproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpareProduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
