# Generated by Django 3.1.1 on 2020-11-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='materials',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='seasons',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
